/*
*   LendBook por:
*   Jonathan Americo Soares -- 42311ETE013
*   Joaquim Vitor castilho ferreira Pedro -- 42111ETE020
*
*/
package blibioteca_v_1_1;

import java.awt.Color;

/**
 *
 * @author bruxo
 */
public class UIRepassword_user extends javax.swing.JPanel {

    /**
     * Creates new form UIRepassword_user
     */
    public UIRepassword_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNewPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bnt_RedefinirSenha = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inputPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        event = new javax.swing.JLabel();

        jLabel3.setText("Nova Senha:");

        bnt_RedefinirSenha.setText("Redefinir senha");
        bnt_RedefinirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_RedefinirSenhaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Esqueceu senha?");

        jLabel5.setText("Telefone:");

        event.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(139, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(inputNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(bnt_RedefinirSenha))
                                .addContainerGap(131, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(event, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNewPass, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bnt_RedefinirSenha)
                                .addGap(30, 30, 30)
                                .addComponent(event, javax.swing.GroupLayout.PREFERRED_SIZE, 17,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)));
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_RedefinirSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bnt_RedefinirSenhaActionPerformed
        String name = UiPainelUser.UserName();
        String phone = inputPhone.getText();
        String newPass = inputNewPass.getText();
        event.setForeground(Color.red);

        if (name.isEmpty() | phone.isEmpty() | newPass.isEmpty()) {
            // System.out.println("\u001B[31m" + "Prencha todos os campos");
            // JOptionPane.showMessageDialog(null, "Prencha todos os campos ", "Erro ao
            // recriar senha", JOptionPane.ERROR_MESSAGE);
            event.setText("Prencha todos os campos");
        } else {

            String rePass = Users.Repassword(name, newPass, phone);

            if (rePass.equals("poo_05") | rePass.equals("poo_02")) {
                // System.err.println(rePass);
                Users.verErr(rePass); // funçao que printa retorno da funçao
                // JOptionPane.showMessageDialog(null, "Telefone ou nome de usuario nao
                // corresponde com cadastro", "Redefinir senha", JOptionPane.ERROR_MESSAGE);
                event.setText("Telefone ou nome de usuario nao corresponde com cadastro");
            } else if (rePass.equals("poo_04")) {
                // System.out.println("\u001B[32m"+"login efetuado com sucesso!");
                Users.verErr(rePass);// funçao que printa retorno da funçao
                // JOptionPane.showMessageDialog(null, "Senha redefinida com sucesso",
                // "Redefinir senha", JOptionPane.PLAIN_MESSAGE);
                event.setText("Senha redefinida com sucesso");

            } else {
                // System.out.println("\u001B[31m"+"Erro inesperado "+rePass);
                event.setText(rePass);
                Users.verErr(rePass);
            }

        }
    }// GEN-LAST:event_bnt_RedefinirSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_RedefinirSenha;
    private javax.swing.JLabel event;
    private javax.swing.JTextField inputNewPass;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
