/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package blibioteca_v_1_1;

import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author bruxo
 */
public class UiRegisteri extends javax.swing.JPanel {

    /**
     * Creates new form UiRegisteri
     */
    public UiRegisteri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JLabel();
        Prencha = new javax.swing.JLabel();
        radioAdm = new javax.swing.JRadioButton();
        Nome = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        inputPhone = new javax.swing.JTextField();
        inputIndent = new javax.swing.JTextField();
        identification = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        inputPassword = new javax.swing.JTextField();
        Registrar = new javax.swing.JLabel();
        event = new javax.swing.JLabel();

        password.setText("Senha:");

        Prencha.setText("Prencha os campos abaixo.");

        radioAdm.setText("Adminitrador");

        Nome.setText("Nome :");

        phone.setText("Telefone:");

        identification.setText("Número identificador");

        btn_register.setText("Registrar");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Registrar.setText("Registrar");

        event.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password)
                    .addComponent(identification)
                    .addComponent(phone)
                    .addComponent(inputPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(Nome)
                    .addComponent(Prencha)
                    .addComponent(Registrar)
                    .addComponent(inputName, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(inputIndent, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register))
                    .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Prencha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phone)
                .addGap(2, 2, 2)
                .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(identification)
                .addGap(2, 2, 2)
                .addComponent(inputIndent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password)
                .addGap(2, 2, 2)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_register)
                    .addComponent(radioAdm))
                .addGap(18, 18, 18)
                .addComponent(event, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        //System.out.println("Apertou");
        String name = inputName.getText();
        String phone = inputPhone.getText();
        String ident = inputIndent.getText();
        String pass = inputPassword.getText();
        boolean adm = radioAdm.isSelected();
        event.setForeground(Color.red);

        if(name.isEmpty() | phone.isEmpty() | ident.isEmpty() | pass.isEmpty()){ //trata erro se tiver algun campo vazio
            System.err.println("Prencha todos os campos");
            //JOptionPane.showMessageDialog(null, "Prencha todos os campos ", "Erro Ao registrar",JOptionPane.ERROR_MESSAGE);
            event.setText("Prencha todos os campos");
            return;
        }else{

            String reAddUser = Users.AddUser(name, phone, ident, pass, adm);// cria usuario guarda no arquivo

            if (reAddUser.equals("poo_09")) {
                //System.err.println(reAddUser);
                Users.verErr(reAddUser); //funçao que printa retorno da funçao
                //JOptionPane.showMessageDialog(null, "Usuario com mesmo nome ja existe", "Registrar novo usuario", JOptionPane.ERROR_MESSAGE);

                event.setText("Usuario com mesmo nome ja existe");
            } else if (reAddUser.equals("poo_10")) {
                //System.out.println("\u001B[32m"+"login efetuado com sucesso!");
                Users.verErr(reAddUser);//funçao que printa retorno da funçao
                //JOptionPane.showMessageDialog(null, "Usuario criado com sucesso", "Registrar novo usuario", JOptionPane.PLAIN_MESSAGE);

                event.setText("Usuario criado com sucesso");
            } else {
                //System.out.println("\u001B[31m"+"Erro inesperado "+reAddUser);
                event.setText(reAddUser);
                Users.verErr(reAddUser);
            }
        }

    }//GEN-LAST:event_btn_registerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Prencha;
    private javax.swing.JLabel Registrar;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel event;
    private javax.swing.JLabel identification;
    private javax.swing.JTextField inputIndent;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JLabel password;
    private javax.swing.JLabel phone;
    private javax.swing.JRadioButton radioAdm;
    // End of variables declaration//GEN-END:variables
}
